---
solr_workspace: /opt/segmint/

solr_create_user: true
solr_user: solr

solr_version: "6.3.0"
solr_mirror: "https://archive.apache.org/dist"

solr_service_name: solr
solr_install_dir: /opt/segmint
solr_install_path: "/opt/segmint/{{ solr_service_name }}"
solr_home: /opt/segmint/solr
solr_port: "8983"

solr_xms: "256M"
solr_xmx: "2048M"

solr_timezone: "UTC"

#solr_cores:
#  - collection1

solr_config_file: /etc/default/solr.in.sh

# Used only for Solr < 5.
solr_log_file_path: /var/log/solr.log
