---
- name: Prerequisites
  include: java.yml

- name: Ensure solr_user group exists.
  group: "name={{ solr_user }} state=present"

- name: Set solr_filename for Solr 4+.
  set_fact:
    solr_filename: "solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] >= '4'"

- name: Ensure solr_user exists.
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_user }}"

- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no
  environment:
    http_proxy: http://172.21.100.144:3128
    https_proxy: http://172.21.100.144:3128

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    creates: "{{ solr_workspace }}/{{ solr_filename }}/CHANGES.txt"
    copy: no

# Install Solr 5+.
- include: install.yml
  when: "solr_version.split('.')[0] >= '5'"

- name: Ensure solr is started and enabled on boot.
  service:
    name: "{{ solr_service_name }}"
    state: started
    enabled: yes
  tags:
   - start_solr

# Create cores, if any are configured.
#- include: cores.yml
#  when: "solr_cores and solr_version.split('.')[0] >= '5'"

# Configure solr.
- include: configure.yml
  when: "solr_version.split('.')[0] >= '5'"
  tags: configure

- include: configs.yml
  tags:
    - configs

- include: datadog.yml
  tags:
    - datadog